const express = require('express');
const router = express.Router();

// Import all route files
const authRoutes = require('./authRoutes');
const bookingRoutes = require('./bookingRoutes');
const clubRoutes = require('./clubRoutes');
const competitionRoutes = require('./competitionRoutes');
const competitionTypeRoutes = require('./competitionTypeRoutes');
const contractRoutes = require('./contractRoutes');
const gameEventRoutes = require('./gameEventRoutes');
const gameRoutes = require('./gameRoutes');
const gameStatusRoutes = require('./gameStatusRoutes');
const goalRoutes = require('./goalRoutes');
const leagueTableRoutes = require('./leagueTableRoutes');
const playerRoutes = require('./playerRoutes');
const playerStatisticsRoutes = require('./playerStatisticsRoutes');
const protectedRoutes = require('./protectedRoutes');
const refereeRoutes = require('./refereeRoutes');
const seasonRoutes = require('./seasonRoutes');
const stadiumRoutes = require('./stadiumRoutes');
const staffAssignmentRoutes = require('./staffAssignmentRoutes');
const staffRoutes = require('./staffRoutes');
const substitutionRoutes = require('./substitutionRoutes');
const teamRoutes = require('./teamRoutes');
const teamStatisticsRoutes = require('./teamStatisticsRoutes');
const userRoleRoutes = require('./userRoleRoutes');
const userRoutes = require('./userRoutes');
const addressRoutes = require('./addressRoutes');
const coachRoleRoutes = require('./coachRoleRoutes');
const competitionTypeTranslationsRoutes = require('./competitionTypeTranslationsRoutes');
const countryRoutes = require('./countryRoutes');
const currencyRoutes = require('./currencyRoutes');
const gameStatusTranslationsRoutes = require('./gameStatusTranslationsRoutes');
const leagueFormatRoutes = require('./leagueFormatRoutes');
const personRoutes = require('./personRoutes');
const playerArchiveRoutes = require('./playerArchiveRoutes');
const playerPositionRoutes = require('./playerPositionRoutes');
const seasonArchiveRoutes = require('./seasonArchiveRoutes');
const staffRoleRoutes = require('./staffRoleRoutes');
const userRoleTranslationsRoutes = require('./userRoleTranslationsRoutes');

// Use all routes
router.use('/auth', authRoutes);
router.use('/bookings', bookingRoutes);
router.use('/clubs', clubRoutes);
router.use('/competitions', competitionRoutes);
router.use('/competition-types', competitionTypeRoutes);
router.use('/contracts', contractRoutes);
router.use('/game-events', gameEventRoutes);
router.use('/games', gameRoutes);
router.use('/game-statuses', gameStatusRoutes);
router.use('/goals', goalRoutes);
router.use('/league-tables', leagueTableRoutes);
router.use('/players', playerRoutes);
router.use('/player-statistics', playerStatisticsRoutes);
router.use('/protected', protectedRoutes);
router.use('/referees', refereeRoutes);
router.use('/seasons', seasonRoutes);
router.use('/stadiums', stadiumRoutes);
router.use('/staff-assignments', staffAssignmentRoutes);
router.use('/staff', staffRoutes);
router.use('/substitutions', substitutionRoutes);
router.use('/teams', teamRoutes);
router.use('/team-statistics', teamStatisticsRoutes);
router.use('/user-roles', userRoleRoutes);
router.use('/users', userRoutes);
router.use('/addresses', addressRoutes);
router.use('/coach-roles', coachRoleRoutes);
router.use('/competition-type-translations', competitionTypeTranslationsRoutes);
router.use('/countries', countryRoutes);
router.use('/currencies', currencyRoutes);
router.use('/game-status-translations', gameStatusTranslationsRoutes);
router.use('/league-formats', leagueFormatRoutes);
router.use('/persons', personRoutes);
router.use('/player-archives', playerArchiveRoutes);
router.use('/player-positions', playerPositionRoutes);
router.use('/season-archives', seasonArchiveRoutes);
router.use('/staff-roles', staffRoleRoutes);
router.use('/user-role-translations', userRoleTranslationsRoutes);

module.exports = router;